kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '17'
  selfLink: /apis/apps/v1/namespaces/foldingathome/deployments/example
  resourceVersion: '244035'
  name: example
  uid: a6839a65-00e1-49a8-97bf-334daf2fa35d
  creationTimestamp: '2021-02-08T01:42:13Z'
  generation: 24
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2021-02-08T03:41:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:alpha.image.policy.openshift.io/resolve-names': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2021-02-08T04:30:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
            'f:spec':
              'f:containers':
                'k:{"name":"foldingathome"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/fah"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/fah/config.xml"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:subPath': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":7396,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                    'k:{"containerPort":36330,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"secret-volume"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:secretName': {}
                'k:{"name":"volume"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2021-02-08T15:28:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
  namespace: foldingathome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foldingathome
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foldingathome
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: config
            defaultMode: 420
        - name: volume
          emptyDir: {}
      containers:
        - name: foldingathome
          image: >-
            image-registry.openshift-image-registry.svc:5000/foldingathome/fah@sha256:c011d5a32431f6baa282f3078afad278ec4dfd9e00a839b346c77465c8cb34b3
          ports:
            - containerPort: 7396
              protocol: TCP
            - containerPort: 36330
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: volume
              mountPath: /fah
            - name: secret-volume
              mountPath: /fah/config.xml
              subPath: config.xml
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 24
  replicas: 2
  updatedReplicas: 2
  readyReplicas: 2
  availableReplicas: 2
  conditions:
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-02-08T04:31:17Z'
      lastTransitionTime: '2021-02-08T03:56:06Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "example-db4495c4b" has successfully progressed.
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-02-08T15:28:54Z'
      lastTransitionTime: '2021-02-08T15:28:54Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
